### PR TITLE
feat: prevent outdated link with GitHub Action

### PR DESCRIPTION
**Pull request by aepfli**
Added a GitHub Action and a makefile to prevent outdated links.

relates: #27

### CODE REVIEW

**Comment by aepfli** [comment]
@agardnerIT i hope this helps to prevent broken links in the future.

Additionally we might want to set those links to tags instead of branches, this way, we will always be uptodate and maybe renovate can help us with keeping those links at the latest release :)

**Review by agardnerIT — APPROVED** [review]
I don't know enough to weigh in the on workflows component of this PR, but the markdown fixes LGTM.

Question: Is the `v0.6.3` dynamic in some way or will the docs need to be updated on each new release?

**Comment by aepfli** [comment]
first iteration hardcoded. and manual. But i want to get renovate bot to provide automated prs for those urls

**Comment by agardnerIT** [comment]
The v0.6.3 link is also now outdated. Furthermore, the link in the playground readme is also broken.

See https://github.com/open-feature/playground/issues/233 for more

**Pull request merged**
