### PR TITLE
Add tracking

### PR DESCRIPTION
**Pull request by agardnerIT**
Signed-off-by: agardnerit <adam@agardner.net>

## This PR
- Adds tracking code to see usage

### CODE REVIEW

**Comment by toddbaert** [comment]
Interesting! I'm not opposed to this. What type of info do we (or killercoda) get here?

Do we need to worry about informing users at all?

**Comment by beeme1mr** [comment]
Hey @agardnerIT, can you elaborate a bit more on how this works? There's a vague reference to [insights in the Killercoda](https://killercoda.com/creators) docs but they don't go into detail. Who owns the AWS account that the tracking event is sent to? How can the data be accessed?

**Comment by beeme1mr** [comment]
@toddbaert I think this should be included in a new spec release. Once the numbering PR is merged, I can start that process.

**Comment by agardnerIT** [comment]
Sure. The tracking they refer to comes if their paid option is chosen. We do not have that functionality as we aren't paying for the platform.

This PR is raised as a workaround to get basic stats.

I'm POSTing to a lambda function this anonymised payload: `{ "tutorial": "openfeature_demo","pageName": "finish.md" }`

Which means we can see which how many times each step is loaded, but nothing more. No user data is sent. The data is logged into Cloudwatch and a CW dashboard is created

The AWS account is not publicly accessible but I wonder how we'd do that regardless of "chosen backend" because there's nothing publicly available.

**Comment by agardnerIT** [comment]
@beeme1mr this is getting stale. Can we merge or close as "will not do" please?

**Review by beeme1mr — APPROVED** [review]
We're evaluating using scarf for analytics but it's not ready yet. This is a good start and we can update the scripts when we have something better in place.

**Pull request merged**
